/** UI/content language. Prompt word pools are keyed off this (#18). */
export type Locale = 'en' | 'ru'

/**
 * The curated pool of daily prompt words. Single, concrete, sensory nouns —
 * chosen to unlock specific memories ("Bicycle", "Kitchen"), not abstractions
 * ("Happiness", "Success") which invite essays instead of memories.
 *
 * Order matters only for determinism; selection is hash-based (see
 * daily-prompt.ts). Words may repeat across years — that recurrence is what
 * powers the annual reflection (Epic 9).
 */
export const WORD_POOL: readonly string[] = [
  // people & family
  'Grandmother',
  'Grandfather',
  'Mother',
  'Father',
  'Sister',
  'Brother',
  'Neighbor',
  'Teacher',
  'Stranger',
  'Twin',
  'Guest',
  'Postman',
  // home
  'Kitchen',
  'Attic',
  'Cellar',
  'Balcony',
  'Doorbell',
  'Window',
  'Stairs',
  'Fireplace',
  'Wallpaper',
  'Curtain',
  'Mirror',
  'Clock',
  'Lamp',
  'Sofa',
  'Pillow',
  'Quilt',
  'Carpet',
  'Key',
  'Fence',
  'Gate',
  'Yard',
  'Garden',
  'Garage',
  'Roof',
  // food & drink
  'Bread',
  'Soup',
  'Pancake',
  'Porridge',
  'Jam',
  'Honey',
  'Apple',
  'Watermelon',
  'Cherry',
  'Strawberry',
  'Mushroom',
  'Potato',
  'Pickle',
  'Chocolate',
  'Candy',
  'Lemonade',
  'Tea',
  'Coffee',
  'Milk',
  'Butter',
  'Cheese',
  'Dough',
  'Cinnamon',
  'Birthday cake',
  // objects
  'Bicycle',
  'Radio',
  'Telephone',
  'Television',
  'Cassette',
  'Record',
  'Camera',
  'Photograph',
  'Letter',
  'Postcard',
  'Envelope',
  'Stamp',
  'Suitcase',
  'Umbrella',
  'Wallet',
  'Coin',
  'Watch',
  'Ring',
  'Necklace',
  'Button',
  'Thread',
  'Needle',
  'Scissors',
  'Ribbon',
  'Notebook',
  'Pencil',
  'Ink',
  'Chalk',
  'Eraser',
  'Lunchbox',
  'Thermos',
  'Matches',
  'Candle',
  'Soap',
  'Towel',
  'Comb',
  'Perfume',
  'Blanket',
  'Toy',
  'Doll',
  'Kite',
  'Marbles',
  'Puzzle',
  'Cards',
  'Chess',
  // clothes
  'Shoes',
  'Boots',
  'Mittens',
  'Scarf',
  'Coat',
  'Hat',
  'Dress',
  'Uniform',
  'Pocket',
  'Braid',
  'Haircut',
  // places
  'School',
  'Playground',
  'Library',
  'Bakery',
  'Market',
  'Church',
  'Hospital',
  'Station',
  'Bridge',
  'Courtyard',
  'Village',
  'City',
  'Forest',
  'Field',
  'River',
  'Lake',
  'Pond',
  'Ocean',
  'Mountain',
  'Island',
  'Road',
  'Path',
  'Corner',
  'Rooftop',
  // travel & motion
  'Train',
  'Tram',
  'Bus',
  'Boat',
  'Airplane',
  'Journey',
  'Map',
  'Ticket',
  'Platform',
  'Swing',
  'Sled',
  'Skates',
  // nature & weather
  'Rain',
  'Snow',
  'Storm',
  'Thunder',
  'Fog',
  'Wind',
  'Ice',
  'Puddle',
  'Rainbow',
  'Sunrise',
  'Sunset',
  'Moon',
  'Stars',
  'Shadow',
  'Leaves',
  'Blossom',
  'Grass',
  'Hay',
  'Bonfire',
  'Smoke',
  'Frost',
  'Heatwave',
  // animals
  'Dog',
  'Cat',
  'Horse',
  'Cow',
  'Chicken',
  'Goose',
  'Pigeon',
  'Sparrow',
  'Stork',
  'Bee',
  'Butterfly',
  'Ladybug',
  'Frog',
  'Fish',
  'Hedgehog',
  // seasons & occasions
  'Summer',
  'Winter',
  'Spring',
  'Autumn',
  'Birthday',
  'New Year',
  'Wedding',
  'Harvest',
  'Vacation',
  'Sunday',
  'Morning',
  'Midnight',
  // senses & small moments
  'Song',
  'Dance',
  'Whistle',
  'Bell',
  'Piano',
  'Guitar',
  'Accordion',
  'Lullaby',
  'Story',
  'Secret',
  'Promise',
  'Joke',
  'Nickname',
  'Recipe',
  'Medicine',
  'Bruise',
  'Splinter',
  'Tooth',
  'Sneeze',
  'Yawn',
  'Whisper',
  'Laughter',
  'Queue',
  'Homework',
  'Exam',
  'Prize',
  'Fight',
  'Dare',
  'Hiding place',
  'Treasure',
]

/**
 * The Russian prompt pool (#18) — curated, not a translation of `WORD_POOL`.
 * A literal rendering loses or invents memory-weight ("Lunchbox" has none in
 * Russian; «Дача», «Электричка», «Подъезд», «Валенки» have none in English),
 * so this list was built independently around the same idea: concrete,
 * sensory nouns from an ordinary life, organized in the same categories for
 * upkeep but free to diverge word for word.
 */
export const WORD_POOL_RU: readonly string[] = [
  // люди и семья
  'Бабушка',
  'Дедушка',
  'Мама',
  'Папа',
  'Сестра',
  'Брат',
  'Соседка',
  'Учитель',
  'Незнакомец',
  'Близнец',
  'Гость',
  'Почтальон',
  // дом
  'Кухня',
  'Чердак',
  'Подвал',
  'Балкон',
  'Звонок',
  'Окно',
  'Лестница',
  'Печь',
  'Обои',
  'Штора',
  'Зеркало',
  'Часы',
  'Лампа',
  'Диван',
  'Подушка',
  'Одеяло',
  'Ковёр',
  'Ключ',
  'Забор',
  'Калитка',
  'Двор',
  'Сад',
  'Гараж',
  'Крыша',
  'Подъезд',
  // еда и напитки
  'Хлеб',
  'Суп',
  'Блины',
  'Каша',
  'Варенье',
  'Мёд',
  'Яблоко',
  'Арбуз',
  'Вишня',
  'Клубника',
  'Грибы',
  'Картошка',
  'Огурцы',
  'Шоколад',
  'Конфеты',
  'Компот',
  'Чай',
  'Кофе',
  'Молоко',
  'Масло',
  'Сыр',
  'Тесто',
  'Корица',
  'Торт',
  'Сушки',
  'Семечки',
  // предметы
  'Велосипед',
  'Радио',
  'Телефон',
  'Телевизор',
  'Кассета',
  'Пластинка',
  'Фотоаппарат',
  'Фотография',
  'Письмо',
  'Открытка',
  'Конверт',
  'Марка',
  'Чемодан',
  'Зонт',
  'Кошелёк',
  'Монета',
  'Кольцо',
  'Бусы',
  'Пуговица',
  'Нитка',
  'Иголка',
  'Ножницы',
  'Лента',
  'Тетрадь',
  'Карандаш',
  'Чернила',
  'Мел',
  'Ластик',
  'Портфель',
  'Термос',
  'Спички',
  'Свеча',
  'Мыло',
  'Полотенце',
  'Расчёска',
  'Духи',
  'Плед',
  'Игрушка',
  'Кукла',
  'Воздушный змей',
  'Шарики',
  'Пазл',
  'Карты',
  'Шахматы',
  // одежда
  'Туфли',
  'Сапоги',
  'Варежки',
  'Шарф',
  'Пальто',
  'Шапка',
  'Платье',
  'Школьная форма',
  'Карман',
  'Косичка',
  'Стрижка',
  'Валенки',
  // места
  'Школа',
  'Площадка',
  'Библиотека',
  'Булочная',
  'Рынок',
  'Церковь',
  'Больница',
  'Станция',
  'Мост',
  'Деревня',
  'Город',
  'Лес',
  'Поле',
  'Река',
  'Озеро',
  'Пруд',
  'Море',
  'Гора',
  'Остров',
  'Дорога',
  'Тропинка',
  'Угол',
  'Дача',
  'Огород',
  // путешествия и движение
  'Поезд',
  'Электричка',
  'Трамвай',
  'Автобус',
  'Лодка',
  'Самолёт',
  'Путешествие',
  'Карта',
  'Билет',
  'Платформа',
  'Качели',
  'Санки',
  'Коньки',
  // природа и погода
  'Дождь',
  'Снег',
  'Гроза',
  'Гром',
  'Туман',
  'Ветер',
  'Лёд',
  'Лужа',
  'Радуга',
  'Рассвет',
  'Закат',
  'Луна',
  'Звёзды',
  'Тень',
  'Листья',
  'Цветение',
  'Трава',
  'Сено',
  'Костёр',
  'Дым',
  'Иней',
  'Жара',
  // животные
  'Собака',
  'Кошка',
  'Лошадь',
  'Корова',
  'Курица',
  'Гусь',
  'Голубь',
  'Воробей',
  'Аист',
  'Пчела',
  'Бабочка',
  'Божья коровка',
  'Лягушка',
  'Рыба',
  'Ёжик',
  // времена года и события
  'Лето',
  'Зима',
  'Весна',
  'Осень',
  'День рождения',
  'Новый год',
  'Свадьба',
  'Урожай',
  'Каникулы',
  'Воскресенье',
  'Утро',
  'Полночь',
  // ощущения и маленькие моменты
  'Песня',
  'Танец',
  'Свист',
  'Колокольчик',
  'Пианино',
  'Гитара',
  'Гармошка',
  'Колыбельная',
  'Сказка',
  'Секрет',
  'Обещание',
  'Шутка',
  'Прозвище',
  'Рецепт',
  'Лекарство',
  'Синяк',
  'Заноза',
  'Зуб',
  'Чих',
  'Зевота',
  'Шёпот',
  'Смех',
  'Очередь',
  'Домашнее задание',
  'Экзамен',
  'Приз',
  'Драка',
  'Спор',
  'Тайник',
  'Клад',
]

const WORD_POOLS: Record<Locale, readonly string[]> = {
  en: WORD_POOL,
  ru: WORD_POOL_RU,
}

/** The active prompt pool for a locale — selection logic keys off this (#18). */
export function getWordPool(locale: Locale): readonly string[] {
  return WORD_POOLS[locale]
}

/**
 * Whether `word` could have been drawn from `locale`'s curated pool, or is
 * one of the user's own custom words (#28 — not locale-scoped, so it belongs
 * to every locale equally). Used to detect a word issued under a *different*
 * locale (#34): if it doesn't belong here, a language switch drew it before
 * this one was active.
 */
export function wordBelongsToLocale(
  word: string,
  locale: Locale,
  customWords: readonly string[]
): boolean {
  return getWordPool(locale).includes(word) || customWords.includes(word)
}
